### ISSUE TITLE
Change contact email to office@shtanglitza.ai

### ISSUE THREAD

**Issue by kotlenik** [Shtanglitza/shtanglitza.github.io#1]

**Comment by CMilos88** [comment]
Zdravo , video sam da ste me obelezili da izvrsim promenu.  Kapiram da ovakva promena zaista ne treba kreiranje novog branch-a ali obzirom da do sada nisam "prckao" tudji/vas kod, ipak sam napravio novi branch i tamo izvrsio izmenu koju ste trazili. Ako sve bude ok,kada proverite ,uradicu mergovanje sa main-om. Ako odobrite pusticu pull request. Ono sto me je zbunilo je da sam nakon prvog pristupa main branch-u imao 5k + pending changes koje nisu moje,vidim (source control graph) da su neke stare i do 5 meseci (djordje,vlada) tako da to nisam dirao,ne znam zasto to vidim kao U (untracked) , trebalo bi da sam samo updejtova cljs fajl novim izmenama, mozete proveriti na novom brach-u. Unapred zahvalan !

**Comment by mladvladimir** [comment]
Ako si proverio kako se renderuje u lokalu, slobodno uradi pull request, merge i deploy.

**Comment by CMilos88** [comment]
Jesam, proverio sam lokalno (http://localhost:8088) ,renderuje sve super. Odradicu to cim pre.

**Comment by kotlenik** [comment]
finito
